### ISSUE TITLE
Error in reproducing results

### ISSUE THREAD

**Issue by aliman80** [ferpb/mininet-v2#1]
Hi, thanks for sharing your wonderful work. I am trying to use it on my custom dataset which consists of images and masks. But while trying to train it gives error  from torchvision import tv_tensors
ImportError: cannot import name 'tv_tensors' from 'torchvision'. Can you guide me what am i missing here. Further more i have changed the datapath with my data directory containing both images and masks , is this ok?

Thanks

**Comment by ferpb** [comment]
Thanks for opening the issue. I updated torchvision in the `requirements.txt` file to a newer version that contains the `tv_tensors` module. Yes, you can change the path to the data. If you use the Citycapes loader just make sure to preprocess the labels to generate training labels as done in https://github.com/ferpb/mininet-v2/blob/c294c7f7b24bac2ba948f73e9afbaed111e99465/download_datasets.sh#L10
